name: ldap-client-og
version: 0.4.0
synopsis: Pure Haskell LDAP Client Library
description: Pure Haskell LDAP client library implementing (parts of) RFC 4511.
category: Network
maintainer: matvey.aksenov@gmail.com
copyright: Matvey Aksenov 2015
license: BSD2
extra-source-files:
  - README.markdown
  - CHANGELOG.markdown
github: supki/ldap-client
tested-with:
  - GHC==9.6.6

dependencies:
  - base >= 4.18 && < 5

library:
  dependencies:
    - asn1-encoding
    - asn1-types
    - async
    - bytestring
    - crypton-connection
    - containers
    - network
    - semigroups
    - stm
    - text
  source-dirs:
    src
  ghc-options:
    - -funbox-strict-fields
    - -Wall
    - -Wno-incomplete-uni-patterns
    # - -Werror

tests:
  spec:
    build-tools:
      - hspec-discover
    dependencies:
      - bytestring
      - hspec
      - ldap-client-og
      - process
      - semigroups
    source-dirs:
      test
    main:
      Spec.hs
    ghc-options:
      - -Wall
      - -Wno-incomplete-uni-patterns
      # - -Werror
      - -threaded
      - -with-rtsopts=-N
